### ISSUE TITLE
垃圾库

### ISSUE THREAD

**Issue by suxiaotongsuki** [limuyang2/LPhotoPicker#1]
用gradle根本导入根本没见文件，害我折腾了一个小时，项目导入又蹦出来一堆问题，垃圾库

**Comment by limuyang2** [comment]
不知道你说的问题是什么，请下载demo测试下

**Comment by limuyang2** [comment]
本库已在项目中正式使用，没有发现问题。同样使用在线导包。请仔细阅读ReadMe后，按照步骤操作。如有疑问，请提交Issues

**Comment by gyf19** [comment]
@AdelaCharley  可以选择不用， 但是不要出来骂人， 力挺开源作者
